version: 2
updates:
  
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "nparamonov"
    target-branch: "develop"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "nparamonov"
    target-branch: "develop"
